name: "Run ClickBench on ClickHouse Cloud"
on:
  workflow_dispatch:  # This allows manual trigger from the UI
  schedule:
    - cron: '10 10 * * *'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - csp: 'aws'
            region: 'us-east-1'
            tier: 'production'
            size: [24 48 96 192 360 720]
          - csp: 'aws'
            region: 'us-east-1'
            tier: 'dev'
          - csp: 'gcp'
            region: 'us-east1'
            tier: 'production'
            size: [ 24 48 96 192 360 708 ]
          - csp: 'gcp'
            region: 'us-east1'
            tier: 'dev'
          - csp: 'azure'
            region: 'eastus2'
            tier: 'production'
            size: [ 24 48 96 192 360 708 ]

    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: "[bot] update results for ClickHouse Cloud"
      CI_COMMIT_AUTHOR: github
    steps:
    - uses: actions/checkout@v2.3.2
    - run: |
        export PROVIDER=${{ matrix.csp }}
        export REGION=${{ matrix.region }}
        export TIER=${{ matrix.tier }}
        export MEMORY=${{ matrix.size }}
        
        export ORGANIZATION=${{ secrets.CLICKHOUSE_CLOUD_ORGANIZATION }}
        export KEY_ID=${{ secrets.CLICKHOUSE_CLOUD_KEY_ID }}
        export KEY_SECRET=${{ secrets.CLICKHOUSE_CLOUD_KEY_SECRET }}

        curl https://clickhouse.com/ | sh
        sudo ./clickhouse install -y
        
        cd clickhouse-cloud
        bash cloud-api.sh
        bash collect-results.sh
        
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ env.CI_COMMIT_AUTHOR }}@users.noreply.github.com"

        git add -A
        if git status | grep -q modified
        then
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
        fi
